### ISSUE TITLE
Метод containsGame выдает false при проверке наличия существующих игр

### ISSUE THREAD

**Issue by An980** [An980/Diploma_QA39-K-A#5]
# Описание:

Метод [containsGame ](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L32)в классе [GameStore](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L8) при наличии и проверке игр выдает false.

# Локация дефекта:
https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения: 

1. Открыть класс [GameStoreTest](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java) с помощью IntelliJ IDEA
2. Запустить тест [shouldAddGame](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java#L10)
3. Сравнить результат в консоли

Ожидаемый результат: _Actual: true_
Фактический результат: _Actual: false_

###Скрин:
![image](https://user-images.githubusercontent.com/105739262/186198993-1d6158c1-3693-4b22-bd04-839867afbdf5.png)

# Окружение:
ОС: Microsoft Windows 10
IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
Java: OpenJDK 11

**Comment by KonstantinVelly** [comment]
Внесено изменение в метод:
public boolean containsGame(Game game) {
        for (int i = 1; i **<=** games.size(); i++) {
            if (games.get(i - 1).equals(game)) {
                return true;
            }
        }
        return false;
    }
