### ISSUE TITLE
Метод getSumPlayedTime возвращает 0 и не суммирует общее время игроков

### ISSUE THREAD

**Issue by An980** [An980/Diploma_QA39-K-A#6]
# Описание:

Метод [getSumPlayedTime ](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L75-L77)в классе [GameStore](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L8) не суммирует время проведенное в игре разными игроками и возвращает 0.

# Локация дефекта:
https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения: 

1. Открыть класс [GameStoreTest](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java) с помощью IntelliJ IDEA
2. Запустить тест [shouldSumTwoPlayerTime](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java#L52)
3. Сравнить результат в консоли

Ожидаемый результат: _12_
Фактический результат: _0_

###Скрин:
![image](https://user-images.githubusercontent.com/105739262/186203877-e5139e80-ffa0-4f01-938a-82d0877ab950.png)

# Окружение:
ОС: Microsoft Windows 10
IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
Java: OpenJDK 11

**Comment by KonstantinVelly** [comment]
Внес изменения в метод getSumPlayTime():
public int getSumPlayedTime() {
        int total = 0;
        for (int playtime : playedTime.values()) {
            total += playtime;
        }
        return total;
    }

**Comment by An980** [comment]
Опечатка в тесте:
Expexted должны быть 22 (не 12)
На результат теста не влияет
