### ISSUE TITLE
Метод getMostPlayer возвращает null если значение времени = 1

### ISSUE THREAD

**Issue by An980** [An980/Diploma_QA39-K-A#7]
# Описание:

Метод [getMostPlayer ](https://github.com/An980/Diploma_QA39-K-A/blob/62c35a45b46894fe2a14c5c5bee178fc5fb07f15/src/main/java/ru/netology/GameStore.java#L58-L69) в классе [GameStore](https://github.com/An980/Diploma_QA39-K-A/blob/master/src/main/java/ru/netology/GameStore.java#L8) возвращает null при вводе значения наигранного игроком времени равному 1.

# Локация дефекта: 
https://github.com/An980/Diploma_QA39-K-A/blob/62c35a45b46894fe2a14c5c5bee178fc5fb07f15/src/main/java/ru/netology/GameStore.java#L58-L69)

# Шаги воспроизведения:

1. Открыть класс [GameStoreTest](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java) с помощью IntelliJ IDEA
2. Запустить тест [shouldShowPlayerOneHour](https://github.com/An980/Diploma_QA39-K-A/blob/56405d79c168606b65533cc11b957988b8111bc7/src/test/java/ru/netology/GameStoreTest.java#L133-L142)
3. Сравнить результат в консоли

Ожидаемый результат: _Player One_
Фактический результат: _null_

# Скрин:
![image](https://user-images.githubusercontent.com/105739262/186715285-1f1adb96-6f9c-46e5-835e-44dc5090a2cb.png)

# Окружение:
ОС: Microsoft Windows 10
IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
Java: OpenJDK 11

**Comment by KonstantinVelly** [comment]
Внесены изменения в метод getMostPlayer():
public String getMostPlayer() {
        **int mostTime = 0;**
        String bestPlayer = null;
        for (String playerName : playedTime.keySet()) {
            int playerTime = playedTime.get(playerName);
            if (playerTime > mostTime) {
                mostTime = playerTime;
                bestPlayer = playerName;
            }
        }
        return bestPlayer;
    }
