### ISSUE TITLE
Метод addPlayTime не суммирует значения времени для одного игрока

### ISSUE THREAD

**Issue by An980** [An980/Diploma_QA39-K-A#8]
# Описание:

Метод [addPlayTime](https://github.com/An980/Diploma_QA39-K-A/blob/62c35a45b46894fe2a14c5c5bee178fc5fb07f15/src/main/java/ru/netology/GameStore.java#L46-L52) в классе [GameStore](https://github.com/An980/Diploma_QA39-K-A/blob/master/src/main/java/ru/netology/GameStore.java#L8) не производит суммирование разных значений времени для одно игрока.

# Локация дефекта: 
https://github.com/An980/Diploma_QA39-K-A/blob/62c35a45b46894fe2a14c5c5bee178fc5fb07f15/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения:

1. Открыть класс [GameStoreTest](https://github.com/An980/Diploma_QA39-K-A/blob/88f3e281da94ac08ed47614c91e884e6490afcc4/src/test/java/ru/netology/GameStoreTest.java) с помощью IntelliJ IDEA
2.  Установить точку останова на 163 строке
3. Запустить в режиме отладчика тест [shouldShowSamePlayerTime](https://github.com/An980/Diploma_QA39-K-A/blob/56405d79c168606b65533cc11b957988b8111bc7/src/test/java/ru/netology/GameStoreTest.java#L154-L165)
4. Сравнить результат в консоли (раскрыть store => playedTime)

Ожидаемый результат (для PLayer One): _12_
Фактический результат (для PLayer One): _5_

# Скрин:
![image](https://user-images.githubusercontent.com/105739262/186722375-a8f161cd-492f-4b08-a663-a594339bbe13.png)

# Окружение:
ОС: Microsoft Windows 10
IDE: IntelliJ IDEA 2022.1.2 (Community Edition)
Java: OpenJDK 11

**Comment by KonstantinVelly** [comment]
Внесены изменения в метод addPlayTime:
public void addPlayTime(String playerName, int hours) {
        if (playedTime.containsKey(playerName)) {
            playedTime.put(playerName, playedTime.get(playerName) + **hours**);
        } else {
            playedTime.put(playerName, hours);
        }
    }
